#!/bin/bash

clear

service_name=newsec-dev.service
service_dir=/etc/systemd/system
server_dir=/srv/nodejs/senti/services/newsec/development

service=$service_dir/$service_name

echo Registering newsec service for development ...


if [ ! -e "$service" ]; then
	echo
    echo "newsec service is not installed"
	echo "Installing newsec service ..."
	sudo cp $server_dir/$service_name $service_dir/$service_name
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl start $service_name
else 
    echo "newsec service is already installed"
	echo "Enabling $service ..."
	sudo systemctl enable $service_name
	sudo systemctl daemon-reload
	echo "Starting $service ..."
	sudo systemctl stop $service_name
	sudo systemctl start $service_name
fi 
